import Vapor

public func routes(_ app: Application) throws {
    app.get { _ in "QuestBoard API running" }

    app.post("auth", "login", use: login)
    app.post("auth", "register-by-invite", use: registerByInvite)
    app.post("auth", "password-reset", "request", use: requestPasswordReset)
    app.post("auth", "password-reset", "confirm", use: confirmPasswordReset)

    let authed = app.grouped(BearerTokenMiddleware())

    authed.get("me", use: me)
    authed.get("account", use: getAccount)
    authed.post("account", "password", use: changeOwnPassword)
    authed.post("account", "username-change-requests", use: requestOwnUsernameChange)
    authed.post("auth", "logout", use: logout)
    authed.get("blueprints", use: listBlueprints)
    authed.post("blueprints", use: createBlueprint)
    authed.get("blueprints", ":blueprintID", use: getBlueprint)
    authed.patch("blueprints", ":blueprintID", use: updateBlueprint)
    authed.post("blueprints", ":blueprintID", "merge", use: mergeBlueprint)
    authed.delete("blueprints", ":blueprintID", use: deleteBlueprint)
    authed.post("blueprints", ":blueprintID", "crafters", use: addBlueprintCrafter)
    authed.delete("blueprints", ":blueprintID", "crafters", ":userID", use: removeBlueprintCrafter)
    authed.post("blueprints", "badges", "rename", use: renameBlueprintBadge)
    authed.post("blueprints", "badges", "delete", use: deleteBlueprintBadge)
    authed.get("quests", use: listQuests)
    authed.get("quests", ":questID", use: getQuest)
    authed.post("quests", use: createQuest)
    authed.post("quests", ":questID", "template", use: createTemplateFromQuest)
    authed.patch("quests", ":questID", use: updateQuestDetails)
    authed.post("quests", ":questID", "approve", use: approveQuest)
    authed.patch("quests", ":questID", "status", use: updateQuestStatus)
    authed.patch("quests", ":questID", "delete", use: markQuestDeleted)
    authed.patch("quests", ":questID", "restore", use: restoreQuest)
    authed.get("quests", ":questID", "requirements", use: listRequirementsForQuest)
    authed.post("quests", ":questID", "requirements", use: createRequirement)
    authed.get("requirements", ":requirementID", "contributions", use: listContributionsForRequirement)
    authed.post("requirements", ":requirementID", "contributions", use: createContribution)
    authed.patch("contributions", ":contributionID", use: updateContribution)
    authed.patch("contributions", ":contributionID", "status", use: updateContributionStatus)

    authed.group("admin") { admin in
        admin.get("password-resets", "pending", use: listPendingPasswordResets)
        admin.post("password-resets", ":requestID", "approve", use: approvePasswordReset)
        admin.post("password-resets", ":requestID", "reject", use: rejectPasswordReset)
        admin.get("username-change-requests", "pending", use: listPendingUsernameChangeRequests)
        admin.post("username-change-requests", ":requestID", "approve", use: approveUsernameChangeRequest)
        admin.post("username-change-requests", ":requestID", "reject", use: rejectUsernameChangeRequest)
        admin.post("retention", "quests", "cleanup", use: cleanupOldQuests)
        admin.post("retention", "selected-cleanup", use: cleanupSelectedData)
        admin.get("audit", "events", use: listAuditEvents)
        admin.delete("audit", "events", use: clearAuditEvents)
        admin.get("users", use: listAdminUsers)
        admin.patch("users", ":userID", "role", use: updateUserRole)
        admin.delete("users", ":userID", use: deleteAdminUser)
        admin.get("invites", use: listInvites)
        admin.post("invites", use: createInvite)
        admin.patch("invites", ":inviteID", "revoke", use: revokeInvite)
        admin.get("quest-templates", use: listQuestTemplates)
        admin.post("quest-templates", use: createQuestTemplate)
        admin.get("quest-templates", ":templateID", use: getQuestTemplate)
        admin.patch("quest-templates", ":templateID", use: updateQuestTemplate)
        admin.delete("quest-templates", ":templateID", use: deleteQuestTemplate)
        admin.post("quest-templates", ":templateID", "requirements", use: createQuestTemplateRequirement)
        admin.post("quest-templates", ":templateID", "create-quest", use: createQuestFromTemplate)
        admin.get("data", "export", use: exportAllData)
        admin.get("data", "export", "manifest", use: exportDataManifest)
        admin.get("data", "export", ":section", use: exportDataSection)
        admin.post("data", "import", use: importAllData)
    }
}
